version = '2'

[run]
allow-parallel-runners = true

[issues]
max-same-issues = 0

[linters]
default = 'all'
disable = [
  'depguard',
  'exhaustruct',
  'forcetypeassert',
  'gomodguard',
  'nlreturn',
  'noinlineerr',
  'paralleltest',
  'varnamelen',
  'wsl',
  'wsl_v5'
]

[linters.settings]
[linters.settings.errcheck]
check-type-assertions = true
check-blank = true

[linters.settings.funlen]
lines = -1

[linters.settings.nolintlint]
require-explanation = true
require-specific = true

[linters.exclusions]
generated = 'strict'
paths = [
  'vendor',
  'third_party$',
  'builtin$',
  'examples$'
]

[formatters]
enable = [
  'gci',
  'gofmt',
  'gofumpt',
  'goimports'
]

[formatters.settings]
[formatters.settings.gofumpt]
extra-rules = true

[formatters.exclusions]
generated = 'lax'
paths = [
  'vendor',
  'third_party$',
  'builtin$',
  'examples$'
]
